### ISSUE TITLE
New nav post-launch checklist

### ISSUE THREAD

**Issue by souperneon** [mapzen/metro-extracts#285]
- [ ] Figure out Metro Extracts login stuff https://github.com/mapzen/metro-extracts/pull/283
- [ ]  Keep dropdown open on mobile https://github.com/mapzen/metro-extracts/issues/284
- [ ] Centralize where docs-generator & metro-extract get header from

**Comment by migurski** [comment]
Docs-gen and Extracts both get their headers and footers from a central location:

- https://github.com/mapzen/mapzen-docs-generator/blob/master/Makefile#L89-L93
- https://github.com/mapzen/metro-extracts/blob/master/App/util.py#L84-L88

**Comment by souperneon** [comment]
Moved here https://github.com/mapzen/website/issues/1259
